theme: jekyll-theme-minimal
title: James Odgers
# description: jo816 at ic.ac.uk \n  [google scholar] (https://scholar.google.co.uk/citations?user=hptXR8AAAAAJ&hl=en)
logo: img/headshot.jpeg
show_downloads: false 
