theme: jekyll-theme-minimal
title: James Odgers
description: I am currently a PhD student at Imperial College London, supervised by Prof. Ruth Misener and Dr. Sarah Filippi.. My PhD is a collaboration with Eli Lilly, where I collaborate with Dr. Salvador García Muñoz.
logo: img/headshot.jpg

