theme: jekyll-theme-minimal
title: James Odgers
description: I am currently a PhD student at Imperial College London, working on probabilistic machine learning methods. 
logo: img/headshot.jpg
github: 
  

